version: "2.1"
services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    command: --smallfiles
    
  mongo-init:
    build: ./mongo-init
    links:
    - mongo

  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo
    
# APP  ***************************************************************************************
  call-docker:
    build: .
    ports:
    - 8080:8080
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /call-0.0.1.jar"
    
    
