version: "2.1"
services:
  mongodb:
    image: mongo
    ports:
    - 27017:27017
    restart: always
    
  mongo-init:
    build: ./src/main/resources/mongo-init
    links:
    - mongodb
    
# APP  ***************************************************************************************
  call-docker:
    build: .
    restart: always
    ports:
    - 8080:8080
    links:
    - mongodb
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /call-0.0.1.jar"
    
    
